version: "3.3"
services:

  consul-dc1:
    image: consul:1.6.2
    command:
      - consul
      - agent
      - "-config-file=/config/consul-dc1.hcl"
      - "-advertise=10.5.0.2"
      - "-advertise-wan=192.169.7.2"
    volumes:
      - "../consul_config:/config"
    ports:
      - 8500:8500
    networks:
      dc1:
        ipv4_address: 10.5.0.2
      wan:
        ipv4_address: 192.169.7.2

  # Define web service and envoy sidecar proxy
  web:
    image: nicholasjackson/fake-service:v0.7.3
    entrypoint: ['sh', '-c']
    command:
      - 'apk update && apk add bind-tools && dig @10.5.0.2 -p 8600 payments.service.consul'
    environment:
      LISTEN_ADDR: 0.0.0.0:9090
      # UPSTREAM_URIS: http://localhost:9091
      MESSAGE: "Hello World"
      NAME: web
      SERVER_TYPE: "http"
      HTTP_CLIENT_KEEP_ALIVES: "false"
    networks:
      dc1:
        ipv4_address: 10.5.0.3
    ports:
      - 9090:9090

networks:
  dc1:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
  wan:
    driver: bridge
    ipam:
     config:
       - subnet: 192.169.7.0/24
