version: "3.3"
services:

  consul-dc1:
    image: consul:1.6.2
    command: ["consul","agent","-config-file=/config/consul-dc1.hcl"]
    volumes:
      - "../consul_config:/config"
    ports:
      - 8500:8500
    networks:
      dc1:
        ipv4_address: 10.5.0.2
      wan:
        ipv4_address: 192.169.7.2

  # Define web service and envoy sidecar proxy
  web:
    image: nicholasjackson/fake-service:v0.7.3
    entrypoint: ['sh', '-c']
    command:
      - 'apk update && apk add bind-tools && dig @10.5.0.2 -p 8600 payments.service.consul'
    environment:
      LISTEN_ADDR: 0.0.0.0:9090
      # UPSTREAM_URIS: http://localhost:9091
      MESSAGE: "Hello World"
      NAME: web
      SERVER_TYPE: "http"
      HTTP_CLIENT_KEEP_ALIVES: "false"
    networks:
      dc1:
        ipv4_address: 10.5.0.3
    ports:
      - 9090:9090

  consul-dc2:
    image: consul:1.6.2
    command: ["consul","agent","-config-file=/config/consul-dc2.hcl"]
    volumes:
      - "../consul_config:/config"
    ports:
      - 9500:8500
    networks:
      dc2:
        ipv4_address: 10.6.0.2
      wan:
        ipv4_address: 192.169.7.4

  # Define api service and envoy sidecar proxy for version 2 of the service
  payments_v2:
    image: nicholasjackson/fake-service:v0.7.3
    environment:
      # UPSTREAM_URIS: http://localhost:9091
      LISTEN_ADDR: localhost:9090
      NAME: payments-dc2
      MESSAGE: "PAYMENTS V2"
    networks:
      dc2:
        ipv4_address: 10.6.0.3
  payments_proxy_v2:
    image: nicholasjackson/consul-envoy:v1.6.2-v0.10.0
    environment:
      CONSUL_HTTP_ADDR: 10.6.0.2:8500
      CONSUL_GRPC_ADDR: 10.6.0.2:8502
      SERVICE_CONFIG: /config/payments_v2.hcl
      CENTRAL_CONFIG: "/central_config/web-defaults.hcl;/central_config/currency-defaults.hcl;/central_config/currency-resolver.hcl"
    volumes:
      - "./service_config:/config"
      - "./central_config:/central_config"
    command: ["consul", "connect", "envoy","-sidecar-for", "payments-v2"]
    network_mode: "service:payments_v2"

networks:
  dc1:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
  dc2:
    driver: bridge
    ipam:
     config:
       - subnet: 10.6.0.0/16
  wan:
    driver: bridge
    ipam:
     config:
       - subnet: 192.169.7.0/24
