version: "3.3"
services:

  consul-dc1:
    image: consul:1.6.1
    command:
     - consul
     - agent
     - "-config-file=/config/consul-dc1.hcl"
     - "-advertise-wan=${DC1_SERVER_PUBLIC_IP}"

    volumes:
      - "../consul_config:/config"
    ports:
      - 8500:8500
      - 8300:8300
      - 8302:8302
    networks:
      dc1:
        ipv4_address: ${DC1_SERVER_PRIVATE_IP}

  # Define web service and envoy sidecar proxy
  web:
    image: nicholasjackson/fake-service:v0.7.3
    environment:
      LISTEN_ADDR: 0.0.0.0:9090
      UPSTREAM_URIS: http://localhost:9091
      MESSAGE: "Hello World"
      NAME: web
      SERVER_TYPE: "http"
      HTTP_CLIENT_KEEP_ALIVES: "false"
    networks:
      dc1:
        ipv4_address: ${DC1_SERVICE_WEB_IP}
    ports:
      - 9090:9090
  web_envoy:
    image: nicholasjackson/consul-envoy:v1.6.1-v0.10.0
    restart: always
    environment:
      CONSUL_HTTP_ADDR: ${DC1_SERVER_PRIVATE_IP}:8500
      CONSUL_GRPC_ADDR: ${DC1_SERVER_PRIVATE_IP}:8502
      SERVICE_CONFIG: /config/web_v1.hcl
      CENTRAL_CONFIG: "/central_config/web-defaults.hcl;/central_config/payments-defaults.hcl;/central_config/payments-resolver.hcl"
    volumes:
      - "./service_config:/config"
      - "./central_config:/central_config"
    command: ["consul", "connect", "envoy","-sidecar-for", "web-v1"]
    network_mode: "service:web"


  # Define currency service and envoy sidecar proxy for version 2 of the service
  currency_dc1:
    image: nicholasjackson/fake-service:v0.7.3
    environment:
      LISTEN_ADDR: localhost:9090
      NAME: currency-dc1
      MESSAGE: "2 USD for 1 GBP"
      SERVER_TYPE: "http"
    networks:
      dc1:
        ipv4_address: ${DC1_SERVICE_CURRENCY_IP}
  currency_proxy:
    image: nicholasjackson/consul-envoy:v1.6.1-v0.10.0
    restart: always
    environment:
      CONSUL_HTTP_ADDR: ${DC1_SERVER_PRIVATE_IP}:8500
      CONSUL_GRPC_ADDR: ${DC1_SERVER_PRIVATE_IP}:8502
      SERVICE_CONFIG: /config/currency_dc1.hcl
    volumes:
      - "./service_config:/config"
    command: ["consul", "connect", "envoy","-sidecar-for", "currency-dc1"]
    network_mode: "service:currency_dc1"

  gateway-dc1:
    image: nicholasjackson/consul-envoy:v1.6.1-v0.10.0
    environment:
      CONSUL_HTTP_ADDR: ${DC1_SERVER_PRIVATE_IP}:8500
      CONSUL_GRPC_ADDR: ${DC1_SERVER_PRIVATE_IP}:8502
    ports:
      - 4443:4443
    command: [
      "consul",
      "connect", "envoy",
      "-mesh-gateway",
      "-register",
      "-address", "${DC1_GATEWAY_PRIVATE_IP}:4443",
      "-wan-address", "${DC1_GATEWAY_PUBLIC_IP}:4443",
      "--",
      "-l", "debug"]
    networks:
      dc1:
        ipv4_address: ${DC1_GATEWAY_PRIVATE_IP}

networks:
  dc1:
    driver: bridge
    ipam:
     config:
       - subnet: ${DC1_SUBNET}
