version: "3.3"
services:

  consul-dc1:
    image: consul:1.6.2
    command:
      - consul
      - agent
      - "-config-file=/config/consul-dc1.hcl"
      - "-advertise=${DC1_SERVER_PRIVATE_IP}"
      - "-advertise-wan=${DC1_SERVER_PUBLIC_IP}"
      - "-retry-join=${DC1_RETRY_JOIN_IP}"
    volumes:
      - "../consul_config:/config"
    network_mode: host

  # # Define web service and envoy sidecar proxy
  # web:
  #   image: nicholasjackson/fake-service:v0.7.3
  #   entrypoint: ['sh', '-c']
  #   command:
  #     - "apk update && apk add bind-tools && dig @$DC1_SERVER_PRIVATE_IP -p 8600 payments.service.consul"
  #   environment:
  #     LISTEN_ADDR: 0.0.0.0:9090
  #     # UPSTREAM_URIS: http://localhost:9091
  #     MESSAGE: "Hello World"
  #     NAME: web
  #     SERVER_TYPE: "http"
  #     HTTP_CLIENT_KEEP_ALIVES: "false"
  #     DC1_SERVER_PRIVATE_IP: ${DC1_SERVER_PRIVATE_IP}
  #   network_mode: host
