version: "3.3"
services:

  consul-dc2:
    image: consul:1.6.2
    command:
      - consul
      - agent
      - "-config-file=/config/consul-dc2.hcl"
      - "-advertise-wan=${DC2_SERVER_PUBLIC_IP}"
      - "-retry-join-wan=${DC1_SERVER_PUBLIC_IP}"
    volumes:
      - "../consul_config:/config"
    ports:
      - 8500:8500
      - 8300:8300
      - 8302:8302
    networks:
      dc2:
        ipv4_address: ${DC2_SERVER_PRIVATE_IP}

  # Define api service and envoy sidecar proxy for version 2 of the service
  payments_v2:
    image: nicholasjackson/fake-service:v0.7.3
    environment:
      UPSTREAM_URIS: http://localhost:9091
      LISTEN_ADDR: localhost:9090
      NAME: payments-dc2
      MESSAGE: "PAYMENTS V2"
    networks:
      dc2:
        ipv4_address: ${DC2_SERVICE_PAYMENTS_IP}
  payments_proxy_v2:
    image: nicholasjackson/consul-envoy:v1.6.2-v0.10.0
    environment:
      CONSUL_HTTP_ADDR: ${DC2_SERVER_PRIVATE_IP}:8500
      CONSUL_GRPC_ADDR: ${DC2_SERVER_PRIVATE_IP}:8502
      SERVICE_CONFIG: /config/payments_v2.hcl
      CENTRAL_CONFIG: "/central_config/web-defaults.hcl;/central_config/currency-defaults.hcl;/central_config/currency-resolver.hcl"
    volumes:
      - "./service_config:/config"
      - "./central_config:/central_config"
    command: ["consul", "connect", "envoy","-sidecar-for", "payments-v2"]
    network_mode: "service:payments_v2"

  gateway-dc2:
    image: nicholasjackson/consul-envoy:v1.6.2-v0.10.0
    environment:
      CONSUL_HTTP_ADDR: ${DC2_SERVER_PRIVATE_IP}:8500
      CONSUL_GRPC_ADDR: ${DC2_SERVER_PRIVATE_IP}:8502
    ports:
      - 4443:4443
    command: [
      "consul",
      "connect", "envoy",
      "-mesh-gateway",
      "-register",
      "-address", "${DC2_GATEWAY_PRIVATE_IP}:4443",
      "-wan-address", "${DC2_GATEWAY_PUBLIC_IP}:4443",
      "--",
      "-l", "debug"]
    networks:
      dc2:
        ipv4_address: ${DC2_GATEWAY_PRIVATE_IP}

networks:
  dc2:
    driver: bridge
    ipam:
     config:
       - subnet: ${DC2_SUBNET}
